Various fixes.

diff --git a/distro/archlinux/PKGBUILD b/distro/archlinux/PKGBUILD
--- a/distro/archlinux/PKGBUILD
+++ b/distro/archlinux/PKGBUILD
@@ -1,14 +1,19 @@
-# Creator: Sven-Hendrik Haase <sh@lutzhaase.com>
+# Contributor: Sven-Hendrik Haase <sh@lutzhaase.com>
+# Contributor: Matthias "matthiaskrgr" Krüger
 # Maintainer: Jookia <166291@gmail.com>
 pkgname=desurium-git
-pkgver=20120404
+pkgver=20120424
 pkgrel=1
 pkgdesc="A community-driven digital distribution service for gamers (open source version)"
-arch=(i686 x86_64)
 url="http://github.com/lodle/Desurium"
 license=('GPL3')
-depends=('v8' 'tinyxml' 'sqlite3' 'boost-libs' 'bzip2' 'gtk2' 'openssl' 'curl' 'c-ares' 'libnotify')
-makedepends=('cmake' 'git' 'boost' 'subversion' 'scons')
+arch=('i686' 'x86_64')
+makedepends=('cmake' 'git' 'boost' 'subversion' 'scons' 'gawk' 'gendesk' 'sed')
+depends=('v8' 'tinyxml' 'sqlite' 'boost-libs' 'bzip2' 'gtk2' 'openssl'
+         'curl' 'c-ares' 'libnotify' 'nss' 'libgnome-keyring' 'bison'
+         'cups' 'flex' 'alsa-lib' 'libjpeg-turbo' 'libxpm' 'libx11'
+         'gconf' 'xdg-user-dirs' 'v8' 'flac' 'libpng' 'speex' 'zlib'
+         'xdg-utils' 'libwebp' 'libevent' 'libxslt' 'yasm')
 provides=('desura')
 conflicts=('desura')
 
@@ -20,35 +25,56 @@ build() {
   msg "Connecting to GIT server...."
 
   if [[ -d "$_gitname" ]]; then
-    cd "$_gitname" && git pull origin
+    cd "$_gitname"
+    msg "Removing build files..."
+    # if this fails, git clean -dfx
+    ./build_make_clean.sh || echo "./build_make_clean.sh failed, running  git clean -dfx ..." ; git clean -dfx
+    msg "Updating..."
+    git pull origin --depth 1 --no-tags
     msg "The local files are updated."
   else
-    git clone "$_gitroot" "$_gitname"
+    msg "Cloning..."
+    git clone "$_gitroot" "$_gitname" --depth 1 --single-branch --branch master
   fi
 
   msg "GIT checkout done or server timeout"
   msg "Starting build..."
 
-  rm -rf "$srcdir/$_gitname-build"
-  git clone "$srcdir/$_gitname" "$srcdir/$_gitname-build"
-  cd "$srcdir/$_gitname-build"
-
-  mkdir build && cd build
-  cmake -D32BIT_SUPPORT=0 -DCMAKE_INSTALL_PREFIX=/opt/desura ..
+  cd "$srcdir/$_gitname"
+  if [ ! -d build ] ; then
+    mkdir build
+  fi
+  cd build
+  msg "Running cmake..."
+  cmake -D32BIT_SUPPORT=0 -DCMAKE_INSTALL_PREFIX=/usr/share/desurium ..
+  msg "Running make..."
   make
-
-  cd ..
-  ./getceflibs.sh
 }
 
 package() {
-  cd "$srcdir/$_gitname-build"
+  cd "$srcdir/$_gitname/build"
 
-  cd build
+  msg "Compiling into pkgdir this time..."
   make DESTDIR="$pkgdir/" install
 
-  cd ..
-  cp ceflibs/* "$pkgdir/opt/desura/lib"
+  cd $srcdir
+
+  mkdir -p ${pkgdir}/usr/bin
+  ln -sT ${pkgdir}/usr/share/desurium/run.sh ${pkgdir}/usr/bin/desurium
+  gendesk ../PKGBUILD
+  cp ${srcdir}/${_gitname}/src/branding_desurium/data/desura_lin.png ./desurium.png
+  sed -i -e 's/Icon=desurium-git.png/Icon=desurium/' \
+    -e 's/Exec=desurium-git/Exec=desurium/' \
+    -e 's/Name=Desurium-git/Name=Desurium/' ${pkgname}.desktop
+  
+  install -m644 -D \
+    desurium.png \
+    ${pkgdir}/usr/share/icons/hicolor/256x256/apps/desurium.png
+
+  desktop-file-install -m 644 --dir ${pkgdir}/usr/share/applications/ ${pkgname}.desktop
+
+  msg "Compiling done"
+
 }
 
 # vim:set ts=2 sw=2 et:
